# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true
command_timeout = 1000 # 1 second

# The character module shows a character (usually an arrow) beside where the text is entered in your terminal.
#[character] # The name of the module we are configuring is "character"
#error_symbol = "[âœ—](bold red) " # The "error_symbol" segment is being set to "âžœ" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
# The username module shows active user's username
#[username]
#style_user = "white bold"
#style_root = "black bold"
#format = "[$user]($style) "
#disabled = false
#show_always = true

[lua]
format = "via [ðŸŒ• $version](bold blue)"

[kotlin]
symbol = "ðŸ‡°"

[zig]
symbol = "îš© "

[java]
symbol = "î‰– "

[gradle]
symbol = "î™  "

[git_status]
format = '([\[$ahead_behind\]]($style) )'
conflicted = " conflicted "
ahead = "ahead"
behind = "behind"
diverged = "diverged"
up_to_date = "âœ“"
untracked = "untraked"
stashed = "stashed"
modified = "modified"
staged = '[++\($count\)](green)'
renamed = "renamed"
deleted = "deleted"
